services:
  mysql:
    image: mysql:8.3.0
    container_name: fa_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:7.0.5
    container_name: fa_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fitness_activity_db
    volumes:
      - mongo:/data

volumes:
  mysql:
  mongo: