spring:
  application:
    name: ai-service
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27017
      database: fitness_ai_db
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

server:
  port: 8083
