spring:
  application:
    name: activity-service
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27017
      database: fitness_activity_db
      authentication-database: admin

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
